from google.adk.agents.llm_agent import Agent
from ExtractorAgent.agent import root_agent as extractor_agent
from AnalyzerAgent.agent import root_agent as analyzer_agent
from ReviewerAgent.agent import root_agent as reviewer_agent
from CitationAgent.agent import root_agent as citation_agent
from TheoryAssumptionsAgent.agent import root_agent as theory_agent
from BaselinesNoveltyAgent.agent import root_agent as baselines_agent
from RobustnessFailureAgent.agent import root_agent as robustness_agent
from MergerAgent.agent import root_agent as merger_agent  # Master Coordinator
from MasterAgent.tools import extract_main_paper_content

root_agent = Agent(
    model="gemini-3.6-flash",
    name="master_orchestrator_agent",
    description="Trims the base paper to its main content, runs the specialist paper-limitation agents, and forwards findings to the merger agent for synthesis.",
    instruction="""
You are the Master Orchestrator Agent for scientific paper limitation analysis.

For every paper you receive:

0. First call extract_main_paper_content with the uploaded base paper's artifact filename.
   This returns paper_content trimmed to only the main content (through Conclusion,
   Limitations, and Ethical/Broader Impact Statement) -- References, Bibliography,
   Acknowledgments, and Appendix are already removed. If cutoff_found is false, use
   paper_content as returned; do not fetch the raw file yourself.
1. Call ALL specialist agents, passing them ONLY the returned paper_content text
   (never the raw artifact/file) as the paper content, plus for citation_agent the
   cited/citing paper information if provided:
   - extractor_agent
   - analyzer_agent
   - reviewer_agent
   - citation_agent
   - theory_agent
   - baselines_agent
   - robustness_agent
2. Collect all outputs.
3. ALWAYS call merger_agent last with all collected outputs.
4. NEVER perform limitation analysis yourself.
5. NEVER generate the final merged list yourself.
6. Return only the response generated by merger_agent.
""",
    tools=[extract_main_paper_content],
    sub_agents=[
        extractor_agent, analyzer_agent, reviewer_agent, citation_agent,
        theory_agent, baselines_agent, robustness_agent,
        merger_agent,
    ],
)